name: release
on:
  push:
    branches:
      - main
      - releases/*

permissions:
  id-token: write
  contents: read

jobs:
  code:
    uses: repobuddy/.github/.github/workflows/pnpm-verify.yml@v1
    with:
      os: '["ubuntu-latest"]'

  release:
    uses: repobuddy/.github/.github/workflows/pnpm-release-changeset.yml@v1
    needs: code
    secrets: inherit

  docgen:
    permissions:
      contents: write
    uses: repobuddy/.github/.github/workflows/pnpm-docs.yml@v1
    needs: release
    if: github.ref == 'refs/heads/main'
    with:
      publish-dir: ./libs/storybook/storybook-static
